### ISSUE TITLE
No releases available

### ISSUE THREAD

**Issue by WvanWaas** [damianeickhoff/HaCasa#18]
Although the documentation has a "releases" button there is no release available. Are there any plans to tag a version anytime soon or should I build it myself?

**Comment by damianeickhoff** [comment]
Thats the plan! I'm going to pick this project back-up somewhere this week!

**Comment by WvanWaas** [comment]
Thank you I'll will wait for that update for now

**Comment by BerrisNO** [comment]
Release link still not working.
You may want to update the documentation temporarily to reflect this.

The theme looks real nice!

**Comment by cloudbr34k84** [comment]
just fell for the ol release link lol

**Comment by damianeickhoff** [comment]
So there is finally a first release. Not something with a change, but it reflects the docs better.
