### ISSUE TITLE
Google Fonts not loading

### ISSUE THREAD

**Issue by mr-woodapple** [damianeickhoff/HaCasa#20]
So I've installed HaCasa and it's working fine so far, but the Google Font won't load. It looks like this: 
![image](https://github.com/damianeickhoff/HaCasa/assets/39863485/d1b53e4f-5c57-4660-a169-34b45f48c014)

My `configuration.yaml` looks like this:

`lovelace:
  mode: "storage"
  resources:
    - url: "/hacsfiles/button-card/button-card.js"
      type: "module"
    - url: "/hacsfiles/my-cards/my-cards.js"
      type: "module"
    - url: "/hacsfiles/kiosk-mode/kiosk-mode.js"
      type: module
    - url: "https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
      type: css
  dashboards:
    mini-hass:
      mode: "yaml"
      title: HaCasa
      icon: mdi:script
      show_in_sidebar: true
      filename: "dashboard/HaCasa/main.yaml"`

Any obvious thing I'm missing?

**Comment by andyblac** [comment]
you need to add the resource in UI, as Lovelace storage mode no longer supports adding resources this way. goto SETTINGS -> DASHBOARDS. xlixl on the 3 dots top right and then click on resources. then click on Add Resource  the URL and choose `Stylesheet` as type, restart HA
<img width="164" alt="Screenshot 2024-07-04 at 21 09 43" src="https://github.com/damianeickhoff/HaCasa/assets/77936/bec45267-d966-4866-9257-0799cd36fd23">
<img width="1529" alt="Screenshot 2024-07-04 at 21 10 58" src="https://github.com/damianeickhoff/HaCasa/assets/77936/b5781b04-23c6-4807-9ad5-ba9e9b0925c7">

**Comment by mr-woodapple** [comment]
Cheers, that works. 

Might be worth noting that you need to have "Advanced Mode" toggled on in your user profile to see the three dots in the upper right (it took me a sec to realize that was why I couldn't found the three dots menu).
