### ISSUE TITLE
sensor.weather_forcast_1

### ISSUE THREAD

**Issue by off112a** [damianeickhoff/HaCasa#9]
Hi,

Love your dashboard 🙂

But I wonder if you could share your code for sensor.weather_forcast_1? So I can get the weekdays on the weather card forecast.

**Comment by damianeickhoff** [comment]
Hé,

You can find the code here in the repo. It's under `dashboard/HaCasa/templates/custom_card_weather/custom_card_weather_forecast.yaml`

Just remember that this template is not really ready so let me know if you find some issues or improvements!

**Comment by off112a** [comment]
Hi,

I have the template. 

I wonder if you have the code for this specific sensor, sensor.weather_forcast_1, that you use in the template? 🙂

**Comment by damianeickhoff** [comment]
I use `Buienradar` which is a Dutch weather integration which expose the forecast in the `weather.buienradar` entity.

With that, I just created a helper template for each day. This is the template code for that:

```yaml
{{ as_timestamp(strptime(states.weather.buienradar.attributes.forecast[0].datetime, '%Y-%m-%dT%H:%M:%S%z')) | timestamp_custom("%a") }}
```

**Comment by off112a** [comment]
Perfect. Thank you 🙂

**Comment by RemcoveHA** [comment]
Hello, I've been looking at this for a couple of hours now and I cannot seem to figure it out. I also used chat.gpt to help me but it looks like buienradar is putting its data in a different way then it used to.

It looks like weather.buienradar is not storing its forecast data the same way. I tried the following code in the developer tools sections and it gives me null. {{ state_attr('weather.buienradar', 'forecast') }}

Which means the way you strip the data for the upcomming days wont work anymore. My weather.buienradar has 108 entities and the forecast data is put in all different sensors. It looks like this for me.

![Schermafbeelding 2024-09-11 154708](https://github.com/user-attachments/assets/f937d0e8-9296-41c8-8d75-76f84ff1cb1a)
![Schermafbeelding 2024-09-11 154727](https://github.com/user-attachments/assets/41daa33a-c2bf-4a41-a54a-dcfb191dada9)
![Schermafbeelding 2024-09-11 154745](https://github.com/user-attachments/assets/3777a633-0aea-476b-8ea8-6d795b294dea)

**Comment by RemcoveHA** [comment]
Also another quick question. I see in the code that, depending on the weather it should pick an weather icon however the icons are not provided via your github or explained how to get them / set them up. Can you also explain that part? Thanks!
